import { createFileRoute } from "@tanstack/react-router";
import { PageHero } from "@/components/site/PageHero";
import { CONTACT, U, BRAND_IMAGES } from "@/lib/site-data";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy, SYLUTION" },
      {
        name: "description",
        content:
          "How SYLUTION collects, uses, stores and protects personal and farm data across our website, applications and field deployments.",
      },
      { property: "og:title", content: "Privacy Policy, SYLUTION" },
      { property: "og:description", content: "Our commitments on personal data, farm data and security." },
    ],
  }),
  component: Privacy,
});

const SECTIONS = [
  {
    h: "Information we collect",
    p: "We collect the details you provide through our contact and newsletter forms, name, organisation, email, phone number and message content, as well as anonymous usage statistics from this website. On deployed systems we collect agronomic and device telemetry such as soil moisture, weather, energy and pump status.",
  },
  {
    h: "How we use information",
    p: "We use your information to respond to enquiries, deliver and support projects, improve our products and send updates you have requested. We do not sell personal data to third parties.",
  },
  {
    h: "Farm data ownership",
    p: "Data generated by your farm belongs to you. We process it to operate your systems and, where you consent, in anonymised and aggregated form for research that improves agricultural outcomes.",
  },
  {
    h: "Storage and security",
    p: "Data is stored on access-controlled infrastructure with encryption in transit. Access is restricted to staff who need it to deliver your service.",
  },
  {
    h: "Retention",
    p: "We keep enquiry records for as long as needed to maintain our commercial relationship and to meet legal obligations, after which they are deleted or anonymised.",
  },
  {
    h: "Your rights",
    p: "You may request access to, correction of, or deletion of your personal data at any time by writing to us.",
  },
  { h: "Cookies", p: "This website uses only essential storage needed to remember your language preference." },
];

function Privacy() {
  return (
    <>
      <PageHero
        eyebrow="Legal"
        title="Privacy Policy"
        subtitle="Last updated 1 January 2026. This policy explains how SYLUTION handles personal and farm data."
        image={BRAND_IMAGES.team}
        compact
      />
      <section className="container-x max-w-3xl space-y-8 section-y">
        {SECTIONS.map((s) => (
          <div key={s.h}>
            <h2 className="font-display text-xl font-bold">{s.h}</h2>
            <p className="mt-3 text-sm leading-relaxed text-muted-foreground">{s.p}</p>
          </div>
        ))}
        <div>
          <h2 className="font-display text-xl font-bold">Contact</h2>
          <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
            Questions about this policy can be sent to{" "}
            <a href={`mailto:${CONTACT.email}`} className="text-primary hover:underline">
              {CONTACT.email}
            </a>{" "}
            or to {CONTACT.address}.
          </p>
        </div>
      </section>
    </>
  );
}
